tifapp/TiFShared

api/TiFAPI.ts
api/models/User.ts
domain-models/User.ts

Adds endpoints for the user settings, and migrates the models over from the backend. Specifically based on [this](https://github.com/tifapp/FitnessProjectBackend/pull/223) PR. I also added `canShareArrivalStatus` which is obviously for whether or not we need to post arrivals to the backend.

User Settings Models

---

api/TiFAPI.ts
domain-models/User.ts

Updates the API response of `saveUserSettings` to return the updated settings instead of just the version number. This makes it easy to return the proper settings to the client in the event of 2 simultaneous settings updates on the server.

Update saveUserSettings API response

---

domain-models/Event.ts
domain-models/Settings.ts
domain-models/User.ts

Adds more settings values that we need for the app to `UserSettings`. I also extracted the settings types into a separate file inside `domain-models`.

User Settings: Add Properties

---

.github/workflows/release.yml

This should make the package easier to consume from the other repos. We can refer to the release tag rather than the commit hash.

Add release tag when pushing to main

---

api/models/User.ts
domain-models/Event.ts
domain-models/Settings.test.ts
domain-models/Settings.ts
domain-models/User.ts

Moves the settings types into a `Settings.ts` file.
I also updated the notification settings to include "triggers". We could've easily done an `isXXXNotificationEnabled` property for each notification type, but that felt repetitive and possibly hard to read. Instead, I've made `XXXNotificationTrigger` types of typical string unions, and `UserSettings` can hold onto an array of those triggers. 
For now, there are 3 types of triggers based on our discussions:
1. Event information changes.
2. Event arrivals.
3. Friend requests.
Each one of those types of triggers is a string union with all the possible "trigger" values that can send a push notification to the user.
TASK_kJRwtAGS

Update Settings Types

---

.github/workflows/link-ticket-on-pull-request.yml
.github/workflows/link-ticket.yml
README.md
npm-scripts/auto-pr-util.test.ts
npm-scripts/auto-pr-util.ts

+fix typo in readme
Now "npm run pr TASK_xxxxx" works as well as "npm run pr https://trello.com/c/xxxxx"
Also when opening/editing a PR you can add the ticket id TASK_xxxxx or trello link https://trello.com/c/xxxxx, and the github action will trigger and link the ticket to the pr.
https://trello.com/c/y6zY4kQW/545-github-trello-integration

Run ticket link github action on pr open & edit, and allow urls in pr description and npm run pr script.

---

.github/workflows/link-ticket-on-pull-request.yml
.github/workflows/link-ticket.yml
npm-scripts/auto-pr.ts

Changes:
* Allow for untracked PRs by adding "TASK_UNTRACKED" to the pr body or branch title. This will allow the ticket-link check to pass while not linking the PR to trello. Ideally all of our PRs should be linked to tickets, but in case we want to make minor PRs that arent linked to a ticket, this allows that to happen without resulting in a github action issue.
* When using "npm run pr", ticket id is removed from PR title since it's added to the PR body.
* Pointed ticket-link job to main branch in this repo
TASK_UNTRACKED

Allow untracked PRs & Remove ticket id from the PR title when using "npm run pr"

---

domain-models/Event.ts

The `EventEditSchema` did not work properly when validating on the frontend. Mainly, Zod would accept a `LocationCoordinate2D` as if it were a `Placemark`, and therefore it would return an empty object instead of the coordinate. This was because `Placemark` can be a completely empty object and still be valid, so Zod used the `PlacemarkSchema` when parsing a `LocationCoordinate2D`. Technically, a `LocationCoordinate2D` is a valid placemark because even having 0 placemark keys means that the object is valid.
To fix this, I added a `type` field to each union case of the `EventEditLocation` type. This way, the schema won't default to the wrong schema in the `z.union`.
https://trello.com/c/4I9AsAG3

Edit Event: Update Zod Schema

---

npm-scripts/prepare.ts
package.json
tsconfig.json

See https://github.com/tifapp/FitnessProjectBackend/pull/269
Default behavior now is not building JS unless env.TIFSHARED_JS is set to true.
TASK_UNTRACKED

Do not build js by default + Use prepare script

---

lib/Result.test.ts
lib/Result.ts

Extend the promise passed to promiseResult() rather than constructing a new promise
TASK_UNTRACKED

Result optimization

---

.github/workflows/test.yml
package-lock.json
package.json

For dependencies that are actually used in the main project (ex. zod, linkify) we should use peer dependencies to ensure the main project uses versions that TiFShared is compatible with.
TASK_UNTRACKED

Use peer dependencies to sync TiFShared package versions with the main project

---

lib/URL.test.ts
lib/URL.ts

We use the urlString() util without a baseUrl to construct the endpoints in backend tests.
TASK_UNTRACKED

Allow optional baseurls

---

api/models/FixedDateRange.test.ts
api/models/FixedDateRange.ts
domain-models/ColorString.test.ts
domain-models/ColorString.ts
domain-models/User.test.ts
domain-models/User.ts
lib/Types/HelperTypes.ts
lib/Zod.test.ts
lib/Zod.ts

Purpose: Complex optional parseable schemas may have multiple different possible validation errors. The current implementation decouples the parsing from the error message, making it difficult to return various error messages from the result of the parse.
Ex.
Proposed Solution: Allow validation errors to be thrown from the parsing function.
Results:
Allows zod errors within the parseable to be propagated.
Allows multiple error messages per optionalParseable schema.
Examples:
Other issues: 
It's difficult to read the original arg from the custom error message, especially when the arg is a deep object. I attempted to wrap it with a JSON.stringify() to make it readable, but then found that zod wraps the custom error in another JSON.stringify(), which still makes it difficult to read and …

Zod optional parseable update

---

api/TiFAPI.ts
api/models/Error.ts
api/models/Event.test.ts
api/models/Event.ts
api/models/FixedDateRange.test.ts
api/models/FixedDateRange.ts
api/models/User.ts
domain-models/ColorString.ts
domain-models/Event.ts
domain-models/FixedDateRange.test.ts
domain-models/FixedDateRange.ts
domain-models/Settings.ts
domain-models/TodayOrTomorrow.ts
domain-models/User.ts
lib/Date.ts

Our zod schemas are encoded in the api spec and then deployed to AWS.
Zod unions get converted to "anyOf" fields in the spec, which isn't supported by AWS unfortunately.
https://github.com/tifapp/FitnessProjectBackend/actions/runs/10954197483/job/30415882552
This PR modifies the problematic schemas to be compatible with AWS' api requirements, particularly replacing union schemas with enum schemas. There are also other schema changes to align with the backend api integration.
Major changes:
* The "themToYou"/"youToThem" statuses are replaced with an easier-to-understand "userRelations" enum. 
* updatedAt/createdAt fields renamed to updatedDateTime/createdDateTime for clarity
* Nullable fields changed to Optionals for requests and responses
* StringDateSchema replaced with z.coerce.date(), …

Update api types

---

api/models/FixedDateRange.ts
domain-models/ColorString.ts
domain-models/User.ts
lib/Types/HelperTypes.ts
lib/Zod.test.ts
lib/Zod.ts

The previous Zod update removed proper type inference from the custom schemas. https://github.com/tifapp/TiFShared/pull/65
This pr fixes that and simplifies the usage by accepting a direct zod schema and inferring the input/output from it.
TASK_UNTRACKED

Zod optionalparseable - Fix zod inferred type and change type signature

---

lib/Zod.test.ts
lib/Zod.ts

OptionalParseable would override previous values in an async context, probably due to the global parsedValue. This PR fixes it by keeping the parsed value within the custom() method and persisting the errors globally instead.
TASK_UNTRACKED

OptionalParseable async behavior

---

lib/Array.test.ts
lib/Array.ts

Copies the array shuffle method from [Sean's prototype PR](https://github.com/tifapp/FitnessProject/pull/413/files/d68829cad4bef0960a88c82a50b550d2bac014c8#diff-66284dbac825b054a1a0355c2ebfd984a86096e710abd17176cfea26cb8964e7).
https://trello.com/c/u74wFpA8/805-seans-prototype

Array Shuffle Extension

---

lib/JWT.test.ts
lib/JWT.ts

The Rudeus Editor frontend needs to be able to parse the user details from the JWT that the Rudeus Server signs. I suspect that we will do something similar for the alpha of the main app, so I have moved this generic function to parse the body of a JWT without verifying it here.
https://trello.com/c/tF0FfaJ6

JWT Body Parsing

---

api/APIClient.test.ts
api/APIValidation.ts
api/TiFAPI.ts
api/Transport.test.ts
api/Transport.ts

Genericizes the API Transport and API Client Validation middlewares to allow custom loggers and names to be passed such that we aren't stuck the TiF name when working with other APIs.
https://trello.com/c/tF0FfaJ6

More API Genericization

---

api/TiFAPISchema.ts
specs.json

Auth in our alpha will just return a permanent JWT so that we don't have to see users churn through the auth flow before giving us feedback on the app. So  changed the `createUserProfile` endpoint schema to return an auth token when the user provides us their name.
TASK_UNTRACKED

Alpha Auth

---

domain-models/ColorString.ts
domain-models/User.ts
lib/Database.ts

To interpolate classes into SQL queries on the backend, we were using a weird if statement mapping that checked if a value was either `ColorString` or `UserHandle`. To ensure that we don't forget to add other cases of rich value classes to that if statement, we can use a simple `DatabaseValueConvertible` interface.
TASK_UNTRACKED

`DatabaseValue`

---

.github/workflows/test.yml
api/APIClient.test.ts
domain-models/User.test.ts
lib/Result.test.ts
lib/Result.ts
package.json
tsconfig.test.json

This pr fixes some typos in Result.ts and re-enables type checking and adds type assertions to Result.test.ts to prevent typescript regressions.
Fix result.ts errors
Add type assertions to the test file
Remove ts-nocheck on result.ts
TASK_UNTRACKED

result type fix

---

api/TiFAPISchema.ts
specs.json

Merges the arrival and departure endpoints into 1 endpoint called `updateArrivalStatus`. The caller will now pass `"arrived"` or `"departed"` for the status.
https://trello.com/c/djNmQxmM

Merge Arrive and Depart Endpoints

---

lib/AddressFormatting.ts

AWS maps the location name "Unknown Location" to this Arkansas place
We should instead make it return undefined and format it on the front end.
https://github.com/tifapp/FitnessProjectBackend/pull/299
TASK_UNTRACKED

Address formatting - return undefined for unknown addresses

---

domain-models/Event.ts

Increases it from 10 seconds to 1 day, this fixes a really annoying validation bug on the frontend, where the user would only have 10 seconds to create an event before it becomes invalid.
TASK_UNTRACKED

Increase `EventEditSchema` Invalid Date Buffer

---

lib/Middleware.ts

`chain2Middleware` used the names `m1` and `m2` for its function parameters. Occasionally, we would receive error messages such as:
```
m1 is not a function.
```
This message makes it seem like some weird minified code failed, and didn't really communicate that middleware was the issue (costing us many confusion cycles on multiple occasions). Therefore, I renamed these function parameters to have the word `middleware` in them to specify that the middleware was the problem.
TASK_UNTRACKED

m -> middleware

---

api/TransportMiddleware.test.ts
api/TransportMiddleware.ts

Adds an `APIMiddleware` that logs requests that the client sends. It does not include the base URL, but I think having the `apiName` should suffice for that.
TASK_UNTRACKED

Request Logging Middleware

---

api/Transport.ts
api/TransportMiddleware.test.ts
api/TransportMiddleware.ts
lib/UUID.ts
test-helpers/mockAPIServer.ts

- Ensures the entire translated path is used for the request logging.
- Adds response logging.
- Tracks the request with a request id in the logging middleware (we could potentially add this to the client extensions and have be autogenerated on each request).
- Adds the `uuidString` utility from the frontend.
TASK_UNTRACKED

Add Response Logging + Fix Request Logging

---

api/TiFAPISchema.ts
api/models/FixedDateRange.test.ts
api/models/FixedDateRange.ts
lib/Base64URLCoding.test.ts
lib/Base64URLCoding.ts
specs.json

This will allow the user's events to be queried by a date range. The query parameter accepts a base64 URL encoded fixed date range JSON payload. It's easier with query params to require the user to pass the entire json date range payload rather than pass 2 optionals for the start and end date respectively, or having to create an entirely new endpoint that mirrors 98% of the existing one. Ideally, we can transition the live events tracking on the frontend to use the new date range, but that's not needed so I've kept the `maxSecondsToStart` parameter for now.
https://trello.com/c/mcM6k8gP

Add dateRange query parameter to upcomingEvents endpoint

---

api/TiFAPISchema.ts
api/models/Event.ts
api/models/FixedDateRange.ts
lib/Zod.ts
specs.json

Introduces the schema for a new endpoint that will power the user's events timeline present in our upcoming prototypes. The endpoint utilizes a page token that contains the offsets for moving backwards and forwards in the timeline. The user will pass a query parameter indicating which direction in time they want to move in, and the API will request events in that direction. The response contains the updated token which will be passed in with the next request, and 2 boolean fields indicating whether or not the user can move backwards or forwards in time from then on.
The token is not passed in with the first request. In such a case, the API will look for events using the direction, limit, starting at the current date.
The token is passed as a base 64 URL encoded JSON payload as a query …

Events Timeline Endpoint Schema
